name: build package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubntu-latest]
        node_version: [12.x]
    steps:
      - name: check out the source
        uses: actions/checkout@v2
      - name: print source info
        run: |
          echo "print source info"
          ls -al
      - name: use nodejs, version is ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: install dependency packages and show node_modules
        run: |
        npm install --unsafe-perm
        ls -al ./node_modules
