name: build package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubntu-latest]
        node_version: [12.x]
    steps:
      - name: check out the source
        uses: actions/checkout@v2
      - name: print source info
        run: |
          echo "print source info"
          ls -al
